edition = "2021"
# The "Default" setting has a heuristic which splits lines too aggresively.
use_small_heuristics = "Max"
# Prevent carriage returns
newline_style = "Unix"
# Reorder imports
reorder_imports = true
